INSERT INTO public.songs (title, artist, is_played)
VALUES
  ('Primavera', 'Ainda Dúo', false),
  ('Você É Linda', 'Caetano Veloso', false),
  ('Las cosas tienen movimiento', 'Fito Páez', false),
  ('Amándote', 'Rubén Blades', false),
  ('Química', 'Banda de Turistas', false),
  ('Algo Contigo', 'Vicentico', false),
  ('Amor Loco', 'Emmanuel Horvilleur', false),
  ('Enamorado Tuyo', 'El Cuarteto de Nos', false),
  ('Quiero que me llames', 'Conociendo Rusia', false),
  ('Trátame Suavemente', 'Soda Stereo', false),
  ('No Te Imaginas', 'No Te Va Gustar', false),
  ('Arde La Ciudad', 'La Mancha de Rolando', false),
  ('Eres', 'Café Tacvba', false),
  ('The Scientist', 'Coldplay', false),
  ('No Me Importa El Dinero', 'Los Auténticos Decadentes', false),
  ('Limón Y Sal', 'Julieta Venegas', false),
  ('Es Por Ti', 'Juanes', false),
  ('Rayando El Sol', 'Maná', false),
  ('Nuestra Canción', 'Monsieur Periné', false),
  ('Caraluna', 'Bacilos', false),
  ('Nada Fue Un Error', 'Coti', false),
  ('Tu Nombre', 'Coti', false),
  ('Bendita Tu Luz', 'Maná', false),
  ('Lento', 'Julieta Venegas', false),
  ('Amor de Perros', 'Los Piojos', false),
  ('Tan Solo', 'Los Piojos', false),
  ('11 y 6', 'Fito Páez', false),
  ('De Música Ligera', 'Soda Stereo', false),
  ('Mil Horas', 'Los Abuelos de La Nada', false),
  ('Mariposas', 'Los Enanitos Verdes', false),
  ('Tu Cárcel', 'Los Enanitos Verdes', false),
  ('Flaca', 'Andrés Calamaro', false),
  ('Loco (Tu Forma de Ser)', 'Los Auténticos Decadentes', false),
  ('Crimenes Perfectos', 'Andrés Calamaro', false),
  ('Muchacha Ojos de Papel', 'Luis Alberto Spinetta', false),
  ('Seguir viviendo sin tu amor', 'Catupecu Machu', false),
  ('Me Haces Bien', 'Jorge Drexler', false),
  ('La Edad Del Cielo', 'Jorge Drexler', false),
  ('Inoportuna', 'Jorge Drexler', false),
  ('Hablando a Tu Corazón', 'Charly García', false),
  ('Seminare', 'Serú Girán', false),
  ('Quizás, Porque', 'Sui Generis', false),
  ('Fogo e Paixão', 'Wando', false),
  ('Sina', 'Djavan', false),
  ('Sorri, Sou Rei', 'Natiruts', false)
ON CONFLICT DO NOTHING;
